import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create CBI-Next App",
  description: "Generated by create CBI-next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}</body>
    </html>
  );
}
